Xp7 support
tineikt/xp-lib-freemarker pull request #14
Opened 2021-04-14 07:28 UTC by cibietici

This feature branch includes the change to support applications developed in XP7.0. Since this is a major change and we still need the previous master to support XP6.15 the version is set to 2.0.0 and we should make a new release from this branch.

2021-04-14 08:06 UTC, tajakobsen requested changes
Good job! :)

But the README.md file should be updated with information about which versions to use with XP6 and which with XP7.

2021-04-14 08:06 UTC, tajakobsen commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-5.6-bin.zip
Why is this only bumped to 5.6? The official ["library starter" bumps it to 6.4](https://github.com/enonic/starter-lib/blob/master/gradle/wrapper/gradle-wrapper.properties#L6) for XP7.

2021-04-14 08:48 UTC, tajakobsen approved these changes
Looks great! Good job! :+1:

2021-04-14 20:53 UTC, tommytusj approved these changes

2021-04-15 07:32 UTC, tajakobsen approved these changes
Good job!

2021-04-15 11:00 UTC, nitelite approved these changes

2021-04-16 13:32 UTC, tommytusj approved these changes

2021-04-16 13:32 UTC, merged